-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.alarms
(
    id integer NOT NULL,
    "time" date NOT NULL,
    snooze integer,
    CONSTRAINT alarms_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.alarms_o_tasks
(
    id integer NOT NULL,
    id_alarm integer NOT NULL,
    id_task integer NOT NULL,
    CONSTRAINT alarms_o_tasks_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.categories
(
    id integer NOT NULL,
    name text COLLATE pg_catalog."default",
    CONSTRAINT categories_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.frequency
(
    id integer NOT NULL,
    scope text COLLATE pg_catalog."default" NOT NULL,
    placements integer[] NOT NULL,
    hour integer NOT NULL,
    CONSTRAINT frequency_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.milestones_o_tasks
(
    id integer NOT NULL,
    id_milestone integer NOT NULL,
    id_task integer NOT NULL,
    CONSTRAINT milestones_o_tasks_pkey PRIMARY KEY (id_milestone)
);

CREATE TABLE IF NOT EXISTS public.priorities
(
    id integer NOT NULL,
    severity integer,
    difficulty integer,
    prioretized boolean,
    progressive boolean,
    CONSTRAINT priorities_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.responsibilities
(
    id integer NOT NULL,
    id_bou integer NOT NULL,
    penalty integer,
    reward integer,
    CONSTRAINT responsibilities_pkey PRIMARY KEY (id_bou)
);

CREATE TABLE IF NOT EXISTS public.tasks
(
    id integer NOT NULL,
    id_responsibility integer NOT NULL,
    id_frequency integer NOT NULL,
    id_category integer NOT NULL,
    id_priority integer NOT NULL,
    title text COLLATE pg_catalog."default" NOT NULL,
    description text COLLATE pg_catalog."default",
    slack integer,
    dailygoal boolean,
    due date,
    CONSTRAINT tasks_pkey PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS public.alarms_o_tasks
    ADD CONSTRAINT alarms_o_tasks_id_alarm_fkey FOREIGN KEY (id_alarm)
    REFERENCES public.alarms (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.alarms_o_tasks
    ADD CONSTRAINT alarms_o_tasks_id_task_fkey FOREIGN KEY (id_task)
    REFERENCES public.tasks (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.milestones_o_tasks
    ADD CONSTRAINT milestones_o_tasks_id_milestone_fkey FOREIGN KEY (id_milestone)
    REFERENCES public.tasks (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;
CREATE INDEX IF NOT EXISTS milestones_o_tasks_pkey
    ON public.milestones_o_tasks(id_milestone);


ALTER TABLE IF EXISTS public.milestones_o_tasks
    ADD CONSTRAINT milestones_o_tasks_id_task_fkey FOREIGN KEY (id_task)
    REFERENCES public.tasks (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.tasks
    ADD CONSTRAINT tasks_id_category_fkey FOREIGN KEY (id_category)
    REFERENCES public.categories (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.tasks
    ADD CONSTRAINT tasks_id_frequency_fkey FOREIGN KEY (id_frequency)
    REFERENCES public.frequency (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.tasks
    ADD CONSTRAINT tasks_id_priority_fkey FOREIGN KEY (id_priority)
    REFERENCES public.priorities (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.tasks
    ADD CONSTRAINT tasks_id_responsibility_fkey FOREIGN KEY (id_responsibility)
    REFERENCES public.responsibilities (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;